apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: gcr.io/sep4-cloud-deploy/sep4cloudtest:${{ github.sha }}
        ports:
        - containerPort: 3000
        - containerPort: 23
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: tcp
      protocol: TCP
      port: 23
      targetPort: 23
  type: LoadBalancer
