apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: gcr.io/sep4-backendcloud/sep4cloudtest:${{ github.sha }}
        ports:
        - containerPort: 3000
        - containerPort: 23
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - name: https
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: tcp
      protocol: TCP
      port: 23
      targetPort: 23
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: your-ingress
spec:
  tls:
  - hosts:
    - "museguardsep.com"  # Use a placeholder or fake domain
    secretName: sep4-secret
  rules:
  - host: "museguardsep.com"  # Use the same placeholder or fake domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-app-service
            port:
              name: https

