name: CI/CD for MuseGuard

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: sep4-backendcloud
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Configure Google Cloud
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/sep4-backendcloud/sep4cloudtest:${{ github.sha }}

      - name: Update Kubernetes Deployment
        env:
         GITHUB_SHA: ${{ github.sha }}
        run: |
          sed -i 's|gcr.io/sep4-backendcloud/sep4cloudtest:.*|gcr.io/sep4-backendcloud/sep4cloudtest:'"${GITHUB_SHA}"'|' ./.github/workflows/kubernetes-deployment.yaml
      
      - name: Deploy to GKE
        run: |
          gcloud components install kubectl
          gcloud container clusters get-credentials sep4-cluster --zone=europe-north1
          kubectl apply -f ./.github/workflows/kubernetes-deployment.yaml 