on:
  push:
    branches:
      - Test-CloudDeploy

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 18

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and test
        run: |
          npm run build --if-present
          npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gcloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: sep4-backendcloud
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true

      - name: Configure Google Cloud
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/sep4-backendcloud/sep4CloudTest:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy YOUR_SERVICE_NAME \
            --image=gcr.io/sep4-backendcloud/sep4CloudTest:${{ github.sha }} \
            --platform=managed \
            --region=europe-north1 \
            --allow-unauthenticated
